function mathProof(){
    var vec1 = new Vector3(0,0,5)
    var vec2 = new Vector3(1,0,6)
    var vec3 = new Vector3(0,1,7)
    var projPlane = new Plane(vec1,vec2,vec3)
    projPlane.calcEq()
    console.log(projPlane.equation)
    var iHat = projPlane.getIHat()
    var jHat = projPlane.getJHat()
    console.log('i^: ')
    console.log(iHat)
    console.log('j^: ')
    console.log(jHat)
    var lT = new Matrix2x2(iHat.x,jHat.x,iHat.y,jHat.y)
    console.log('Matrix: ')
    console.log(lT)
    lT.invert()
    console.log('Matrix\': ')
    console.log(lT)
    var newVec1 = new Vector2(vec1.x,vec1.y)
    var newVec2 = new Vector2(vec2.x,vec2.y)
    var newVec3 = new Vector2(vec3.x,vec3.y)
    newVec1.matMult(lT.a,lT.b,lT.c,lT.d)
    newVec2.matMult(lT.a,lT.b,lT.c,lT.d)
    newVec3.matMult(lT.a,lT.b,lT.c,lT.d)
    console.log('Vector1*LT: ')
    console.log(newVec1)
    console.log('Vector2*LT: ')
    console.log(newVec2)
    console.log('Vector3*LT: ')
    console.log(newVec3)
  
    lT.invert()
    newVec1.matMult(lT.a,lT.b,lT.c,lT.d)
    newVec2.matMult(lT.a,lT.b,lT.c,lT.d)
    newVec3.matMult(lT.a,lT.b,lT.c,lT.d)
    console.log('Vector1: ')
    console.log(newVec1)
    console.log('Vector2: ')
    console.log(newVec2)
    console.log('Vector3: ')
    console.log(newVec3)
  }